name: fix_map
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_cupertino_localizations: ^1.0.1
  equatable: ^1.0.1
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  intl: ^0.15.8
  shared_preferences: 0.5.3+3
  permission_handler: ^4.0.0
  fluttertoast: ^3.1.3
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+13
  geolocator: ^5.1.5
  flutter_swiper: 1.1.6
  dio: ^3.0.7
  sqflite: ^1.1.7+3
  path_provider: ^1.5.0
  cached_network_image: ^1.1.3
  percent_indicator: ^2.1.1+1
  bloc_test: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.4.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/map/
    - assets/onboarding/